### ISSUE TITLE
File uploads not functional

### ISSUE THREAD

**Issue by chingor13** [GoogleCloudPlatform/elixir-google-api#1]
- [x] Tesla client does not yet support multipart file upload, but a pull request is in progress. See: https://github.com/teamon/tesla/pull/87
- [x] Google Discovery -> OpenApi specification conversion loses data about upload types and paths

This currently affects the following APIs:
* Analytics
* AndroidPublisher
* BigQuery
* ChromeWebStore
* DFAReporting
* Discovery
* Drive
* FusionTables
* GamesConfiguration
* Gmail
* GroupsMigration
* Mirror
* PlayCustomApp
* PlusDomains
* Storage
* YouTube

**Comment by jeroenvisser101** [comment]
@chingor13 is this issue already addressed? #5 is said to enable file uploads but this is still open.

**Comment by chingor13** [comment]
@jeroenvisser101 #5 only fixed the Storage client, and #29 fixed the BigQuery client. All the other APIs are still affected.

The underlying issue is that OpenAPI v2 (swagger) is not descriptive enough to autogen usable clients for file uploads -- you must craft a request body which is not described. The temporary fix (until OpenAPI v3 tools are better) was to use a temporary, technically invalid OpenAPI v2 specification when the code generator can use to make a more usable client.

**Comment by storm255** [comment]
@chingor13  Sorry for the query, but just to be clear - are saying it is possible to generate a package that can access the services affected via a manual process, but not automatically publish it to hex?

If so, is there any guidance anywhere that I can use to generate it locally?

**Comment by chingor13** [comment]
@storm255 There are slight differences between the APIs and how they handle the file uploads. So the issue is not so much generating and pushing package, but rather testing the package to make sure the uploads actually work for each library.

**Comment by storm255** [comment]
@chingor13 Is that something I could set up some integration testing with Hound and some real credentials for each service.  Work across the API to confirm the calls.
