### ISSUE TITLE
Rename repository to elixir-google-client

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/elixir-google-api#27]
I believe this will be more clear, as "Google API" implies the server side logic.

Thoughts? And will there be any impact in Hex on a rename like this?

**Comment by chingor13** [comment]
I have no real issue with the renaming.

The packages on hex would not be affected by this.

**Comment by dazuma** [comment]
I think at this point the time to rename the repo has passed. We should probably just leave it as is for now.
