### ISSUE TITLE
Youtube client is not published on hex.pm

### ISSUE THREAD

**Issue by jesteracer** [GoogleCloudPlatform/elixir-google-api#35]
This client https://github.com/GoogleCloudPlatform/elixir-google-api/tree/master/clients/you_tube is not on hex
{ :google_api_you_tube, "~> 0.1.0" } - gives me not found

**Comment by chingor13** [comment]
YouTube version 0.0.1 is now published to hex. Not that only a few endpoints were actually tested and that these clients are still pretty experimental.

Some APIs require an authenticated token on behalf 
 of a user and must be obtained through an OAuth2 workflow. Here's a link to the documentation about why: https://developers.google.com/youtube/v3/guides/moving_to_oauth
