### ISSUE TITLE
Google Beacon Proximity API activate/deactivate beacon error: no function clause matching in :httpc.request/5

### ISSUE THREAD

**Issue by fdietz** [GoogleCloudPlatform/elixir-google-api#37]
Awesome that there's an elixir api client now! 

I've started testing the API client and got most calls working but got the following error in the activate/deactivate calls:

```
* (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :httpc.request/5
        (inets) httpc.erl:149: :httpc.request(:post, {'https://proximitybeacon.googleapis.com/v1beta1/beacons/3!0123456789abcdef1123000000000003:activate', [{'authorization', 'Bearer ya29.c.Elo8BZjAwNexF3gkUrKn9m-3VGwtAl-s3TTxfvxQvtRziNh-TpRZTJ9DAY_-18zIi0kRFSEsNQWuiCwK6kRFAY_aD3aLQAv_BGAx74sua2AAuTC1yK0xpzLPXZw'}, {'user-agent', 'Elixir'}]}, [autoredirect: false], [], :default)
        (tesla) lib/tesla/adapter/httpc.ex:32: Tesla.Adapter.Httpc.request/2
        (tesla) lib/tesla/adapter/httpc.ex:19: Tesla.Adapter.Httpc.call/2
        (tesla) lib/tesla/middleware/core.ex:6: Tesla.Middleware.Normalize.call/3
        (stdlib) timer.erl:197: :timer.tc/3
        (tesla) lib/tesla/middleware/logger.ex:29: Tesla.Middleware.Logger.call/3
```

I'm aware that this is similar to an already reported issue https://github.com/GoogleCloudPlatform/elixir-google-api/issues/26, but the workaround cannot be applied in this case since the function signature doesn't let me pass a body argument. 

Any help/advice would be appreciated. Many thanks in advance!

**Comment by dazuma** [comment]
I made a note of this in #26 and we're going to be assigning some time to look for a general solution in the coming weeks. I'm going to close this as a duplicate. Please follow #26 for further updates.
