### ISSUE TITLE
Translate API responses not deserializing properly due to wrapping

### ISSUE THREAD

**Issue by dazuma** [GoogleCloudPlatform/elixir-google-api#38]
The response objects for the Translate V2 API are not deserializing properly. This is because the responses are wrapped in a `data` field. That is, the JSON response, instead of:

```
{
   "field1":"data1"
}
```

Instead looks like this:

```
{
  "data": {
    "field1":"data1"
  }
}
```

As far as I can tell (based on the Ruby Apiary client), this is controlled by the following property in the [discovery doc](https://translation.googleapis.com/$discovery/rest?version=v2):

```
{
  ...
  "features": [
    "dataWrapper"
  ],
  ...
}
```

And as far as I can tell, Translate V2 is the only API with this property.

**Comment by chingor13** [comment]
Yep, appears that these responses are all wrapped in a root "data" element and that this is the only API that uses this.

The plan:
1. at discovery doc conversion time, we capture that feature as a vendor extension in openapi (x-datawrapper or something like that)
2. in the template for request builder, if the API has that vendor extension, we'll handle the extra "data" field when the response is first parsed.
