### ISSUE TITLE
Speech client references nonexistent `GoogleApi.Speech.V1.Model.Object`

### ISSUE THREAD

**Issue by Rsullivan00** [GoogleCloudPlatform/elixir-google-api#49]
Creating a longrunning recognize speech request currently errors when decoding the operation result. 

```
** (UndefinedFunctionError) function GoogleApi.Speech.V1.Model.Object.__struct__/0 is undefined (module GoogleApi.Speech.V1.Model.Object is not available)
    GoogleApi.Speech.V1.Model.Object.__struct__()
    (google_api_speech) lib/google_api/speech/v1/deserializer.ex:36: anonymous fn/3 in GoogleApi.Speech.V1.Deserializer.deserialize/5
    (elixir) lib/map.ex:727: Map.update!/3
    (google_api_speech) lib/google_api/speech/v1/model/operation.ex:47: Poison.Decoder.GoogleApi.Speech.V1.Model.Operation.decode/2
    (poison) lib/poison.ex:70: Poison.decode/2
```

`GoogleApi.Speech.V1.Model.Operation` attempts to deserialize metadata and the response with `GoogleApi.Speech.V1.Model.Object`, which doesn't exist.

The [operation documentation](https://cloud.google.com/speech/reference/rest/v1/operations#Operation.FIELDS) references `object`. I'm not too familiar with Swagger/OpenAPI, so I'm not sure if the issue lies in the schema or the Elixir code generation.

**Comment by chingor13** [comment]
Thanks for the report! I'll take a look.

**Comment by chingor13** [comment]
So here's the crux of the issue: `Operation` is a shared object across different APIs. Thus, the `metadata` and `response` fields lack a defined structure in the specification (they include a reference to a structure which is not included in the discovery doc). We'll have to figure out a way to signal that these fields should not be modified - they'll end up just returning the list/map values that `Poison` decodes from the json.

**Comment by Rsullivan00** [comment]
Thanks for looking into it!

From what I've read, it seems having
```json
"type": "object"
```
with no `properties` key is the expected way to handle an unknown nested structure in OpenAPI.

It seems like a possible issue in Swagger Codegen if 
```json
        "response": {
          "additionalProperties": {
            "description": "Properties of the object. Contains field @type with type URL.",
            "type": "any"
          },
          "description": "The normal response ...",
          "type": "object"
        },
```
Is attempting to find an `Object` module when it wasn't given a `$ref` to a type, but rather just `object`.

> We'll have to figure out a way to signal that these fields should not be modified - they'll end up just returning the list/map values that Poison decodes from the json.

Yeah, in my locally linked version of this client, I just removed [these lines](https://github.com/GoogleCloudPlatform/elixir-google-api/blob/master/clients/speech/lib/google_api/speech/v1/model/operation.ex#L47-L48) and everything works great.

**Comment by chingor13** [comment]
Yes removing those lines would work. Unfortunately it's non-trivial. All of the client libraries are generated code using the swagger-codegen project (with custom templates). Swagger-codegen uses mustache templates which by design has almost not logic in templates. Detection of an empty object type would have to happen upstream in swagger codegen's Java code.

**Comment by Rsullivan00** [comment]
[Same thing happens using when I modify their test schema to use the same pattern](https://github.com/swagger-api/swagger-codegen/compare/master...Rsullivan00:rs/elixir-object). 

I think they are detecting empty objects somewhere before they generate the code itself. If I generate Python and Ruby clients with the same schema, they map `metadata` to `object` and `Object`, respectively. Maybe they're intentionally using these classes over `dict` and `hash` for some reason, and there's just no parallel in Elixir since it's not OO?

One other question: do you where `any` in `"type": "any"` comes from? I don't see any mentions of it in OpenAPI specs.

**Comment by Rsullivan00** [comment]
:smile: I just realized you wrote some of the code I'm looking at. Nice :+1:

**Comment by chingor13** [comment]
We just released a new speech client which addresses this issue
