### ISSUE TITLE
Can't override base_url to connect to local PubSub simulator

### ISSUE THREAD

**Issue by jeffdeville** [GoogleCloudPlatform/elixir-google-api#58]
GoogleApi.PubSub.V1.Connection
uses:
`plug Tesla.Middleware.BaseUrl`

instead of 

`Tesla.Middleware.BaseUrlFromConfig`

As a result, it's impossible to try and direct commands to the local Pubsub simulator.

**Comment by chingor13** [comment]
Thanks, for the report.

It looks like BaseUrlFromConfig is being removed from Tesla so we'll need to find a different approach to allow configuring the base url.

**Comment by jeffdeville** [comment]
FWIW, Tesla, like Faraday that it's based on, introduced a ton of complexity for what looked like very little value. Perhaps with this swagger code generator you have there's something it adds, but I'd personally consider dropping it in favor of using the HTTPoison.Base macro instead.  Short of that, it looks like tesla needs to be flexible enough to take it's various plug parameters as function definitions, and invoke them at runtime to allow things to be configurable.  ¯\_(ツ)_/¯

**Comment by chingor13** [comment]
We just released new versions of the client libraries which includes the fix from #81
