### ISSUE TITLE
Sheets documentation

### ISSUE THREAD

**Issue by mbenatti** [GoogleCloudPlatform/elixir-google-api#62]
There's a lack of documentation in these client's,
I'm trying to use the `google_api_sheets` app...

Could you add more documentation, examples like, how to fetch a (private) google spreadsheet... ?

**Comment by dazuma** [comment]
There is basic reference documentation (for example https://hexdocs.pm/google_api_sheets/) but it could definitely be improved. If you have particular suggestions, we'd love to hear from you.

Writing full-blown examples and howtos for hundreds of APIs, however, is a large task, and we're not likely to be able to do it with our small team. We have a small repository of sample code at https://github.com/GoogleCloudPlatform/elixir-samples and pull requests are welcome. But if you need examples for performing particular tasks, I recommend going to the general (language-independent) documentation for the API (such as https://developers.google.com/sheets/api/), and translating from there into your preferred language.

**Comment by dazuma** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/elixir-google-api/issues/24. If you have particular things you'd like to see in the documentation, please feel free to reopen with details.
