### ISSUE TITLE
Tesla update

### ISSUE THREAD

**Issue by carlodicelico** [GoogleCloudPlatform/elixir-google-api#64]
Tesla is [coming up on 1.0](https://github.com/teamon/tesla/tree/v1.0.0-beta.1) pretty soon, and there are some breaking changes.

**Comment by dazuma** [comment]
Thanks for the heads-up. Tesla 1.0 is still not release, but we'll need to keep an eye on it.

**Comment by teamon** [comment]
I have a fork with updates for tesla 1.0, the changes required are https://github.com/cabify/elixir-google-api/commit/fbba493b639c6f92de29e3695a5e729e2d6ed78d

You can try it with for example

```elixir
{:google_api_datastore, github: "cabify/elixir-google-api", branch: "tesla-1.0-gen", sparse: "clients/datastore"}
```

As for tesla 1.0 release itself - the more people confirms the `1.0.0-beta1` is working fine and the upgrade path is smooth the sooner it will be released.

**Comment by parkerjm** [comment]
Tesla 1.0.0 was released today: https://github.com/teamon/tesla/releases/tag/v1.0.0 thanks @teamon

**Comment by chingor13** [comment]
We just released new versions of the client libraries that use ttesla 1.0
