### ISSUE TITLE
CalendarApi.Events.calendar_events_list wrong documentation

### ISSUE THREAD

**Issue by amit115532** [GoogleCloudPlatform/elixir-google-api#78]
GoogleApi.Calendar.V3.Api.Events.calendar_events_list optional parameter: privateExtendedProperty: is of type String.t but docs specify [String.t] (with list)

using the list version will cause the url to look like this: 
?privateExtendedProperty%5b%5d=x%3Dx
notice the %5b%5d after the parameter name.

GoogleApi just ignores this parameter.

**Comment by chingor13** [comment]
Thanks for reporting this. It looks like the API expects repeated query parameters instead of the array form:
```
GET https://www.googleapis.com/calendar/v3/calendars/{CALENDAR_ID}/events?privateExtendedProperty=foo%3Dbar&privateExtendedProperty=qwer%3Dasdf&key={YOUR_API_KEY}
```
Will need to figure out how this is determined vs. using privateExtendedProperty[]= in the query

**Comment by chingor13** [comment]
We just released a new Calendar API with this fix.
